branches:
  only:
  - master
  - staging
language: node_js
node_js:
  - "node"
before_install:
- npm install -g @vue/cli
before_script:
- cd ui
- if [ "$TRAVIS_BRANCH" = "staging" ]; then sed -i "s/\/master\//\/staging\//g" src/main.js ; fi
- npm install
script: npm run build
deploy:
  - provider: s3
    access_key_id: AKIA3VZOTCNUBLX4W57P

    secret_access_key:
      secure: "Z6F+6KorrdeRTwmuQXrgaDlRivQ2jMdO7/erb5EbdfSr2OnaJRKH8n1WyNMUDPLh4F1yX9RN0OPXSux8uGZeuUctUH9sJsB7WvQpFJqabj0W6VylxSKznmJFWrHiiqlES+M2kxUUo6UauCd7PfJq5M8DVjioCs0XQtPk0kWPEGdO0/KlICFOo3fCwAVfJhIL7GQdtQjeNHPi+4MzAxWnrrZYYfc6uZHNKs1wV4l0RFmGdUZCKrZlz5byHqYomJRX6YN8YWN02k7FHGa0FVywVSCkNYqtZCdVc5jXjNFdA/CpM05dZ2AVq1LUBmzh/U/eZ4Y3SZsoCuUhT+1Qs6ohnkmZaUFCy6/G+RWx/RlNxDQRqKiUkwA1YwMje51ukzB7JgN+rrA1WFb5aPONyTs4VL4oJhRcUQpEjLDHykrm3ZM/ySxO8tk/09KCaYYGcL6z6MBC7EUGuo8ewvvTyJPOrKjMYXQqNG9iLgMPeMBvYM3pO+MWo3BR7Qr9kXo8CUO74UNlYUmknabPsRAp3m7E83hxGDi3/9SNtR4XKnYxSdHh7DZXOKYqSpHLfd3rl+XZQglc0u6yYTcEjjQxeJfdLjNeeYR3te8KxhEo/FVbJtj4m8dt75dBzFO74Dja1Txm/IMZTE7LpxuG9MoVShfAlMOsi4BidC8PLewndQpzrXo="

    bucket: staging.linuxkernelcves.com
    local-dir: dist
    acl: public_read
    skip_cleanup: true
    on:
      repo: nluedtke/linux_kernel_cves
      branch: staging
  - provider: s3
    access_key_id: AKIA3VZOTCNUBLX4W57P

    secret_access_key:
      secure: "Z6F+6KorrdeRTwmuQXrgaDlRivQ2jMdO7/erb5EbdfSr2OnaJRKH8n1WyNMUDPLh4F1yX9RN0OPXSux8uGZeuUctUH9sJsB7WvQpFJqabj0W6VylxSKznmJFWrHiiqlES+M2kxUUo6UauCd7PfJq5M8DVjioCs0XQtPk0kWPEGdO0/KlICFOo3fCwAVfJhIL7GQdtQjeNHPi+4MzAxWnrrZYYfc6uZHNKs1wV4l0RFmGdUZCKrZlz5byHqYomJRX6YN8YWN02k7FHGa0FVywVSCkNYqtZCdVc5jXjNFdA/CpM05dZ2AVq1LUBmzh/U/eZ4Y3SZsoCuUhT+1Qs6ohnkmZaUFCy6/G+RWx/RlNxDQRqKiUkwA1YwMje51ukzB7JgN+rrA1WFb5aPONyTs4VL4oJhRcUQpEjLDHykrm3ZM/ySxO8tk/09KCaYYGcL6z6MBC7EUGuo8ewvvTyJPOrKjMYXQqNG9iLgMPeMBvYM3pO+MWo3BR7Qr9kXo8CUO74UNlYUmknabPsRAp3m7E83hxGDi3/9SNtR4XKnYxSdHh7DZXOKYqSpHLfd3rl+XZQglc0u6yYTcEjjQxeJfdLjNeeYR3te8KxhEo/FVbJtj4m8dt75dBzFO74Dja1Txm/IMZTE7LpxuG9MoVShfAlMOsi4BidC8PLewndQpzrXo="

    bucket: linuxkernelcves.com
    local-dir: dist
    acl: public_read
    skip_cleanup: true
    on:
      repo: nluedtke/linux_kernel_cves
      branch: master

